# Generated by Django 5.2.6 on 2025-10-31 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('superadmin', '0002_securityevent_created_at_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='superadmin.business'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='superadmin.business'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('business', 'name')},
        ),
    ]
