# Generated by Django 5.2.6 on 2025-10-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_type', models.CharField(choices=[('CODE128', 'Code 128'), ('CODE39', 'Code 39'), ('EAN13', 'EAN-13'), ('UPC-A', 'UPC-A')], default='CODE128', max_length=10)),
                ('barcode_width', models.IntegerField(default=200)),
                ('barcode_height', models.IntegerField(default=100)),
                ('display_text', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Barcode Settings',
            },
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_address', models.TextField()),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business/logo/')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
