# Generated by Django 5.2.6 on 2025-10-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='business_address',
            field=models.TextField(default='123 Business Street, City, Country'),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='business_email',
            field=models.EmailField(default='info@smartsolution.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='business_name',
            field=models.CharField(default='Smart Solution', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='business_phone',
            field=models.CharField(default='+1 (555) 123-4567', max_length=20),
        ),
    ]
