# Generated by Django 5.2.6 on 2025-10-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_businesssettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='currency_symbol',
            field=models.CharField(default='FRW', max_length=10),
        ),
    ]
