# Generated by Django 5.2.6 on 2025-10-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_businesssettings_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='expiry_alert_days',
            field=models.IntegerField(default=7, help_text='Number of days before expiry to send alerts'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='near_expiry_alert_days',
            field=models.IntegerField(default=30, help_text='Number of days before expiry to send near expiry alerts'),
        ),
    ]
