# Generated by Django 5.2.7 on 2025-10-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_businesssettings_expiry_alert_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP (Gmail, SendGrid, etc.)'), ('django.core.mail.backends.console.EmailBackend', 'Console (Development - Print to Terminal)'), ('django_ses.SESBackend', 'Amazon SES')], default='django.core.mail.backends.smtp.EmailBackend', max_length=100)),
                ('email_host', models.CharField(blank=True, help_text='SMTP server address (e.g., smtp.gmail.com)', max_length=100, null=True)),
                ('email_port', models.IntegerField(default=587, help_text='SMTP port (587 for TLS, 465 for SSL)')),
                ('email_host_user', models.CharField(blank=True, help_text='Email address or username', max_length=100, null=True)),
                ('email_host_password', models.CharField(blank=True, help_text='Password or app password', max_length=100, null=True)),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('default_from_email', models.CharField(default='Inventory Management System <webmaster@localhost>', help_text='Default sender email address', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
