# Generated by Django 5.2.6 on 2025-11-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_branch_remove_customer_created_by_and_more'),
        ('superadmin', '0004_branch_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='superadmin.branch'),
        ),
    ]