# Generated by Django 5.2.6 on 2025-11-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_branch'),
        ('superadmin', '0004_branch_manager'),
    ]

    operations = [
        # Check if the column exists before adding it
        migrations.RunSQL(
            # Forward operation - only add column if it doesn't exist
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='customers_customer' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE customers_customer 
                    ADD COLUMN branch_id integer REFERENCES superadmin_branch(id) DEFAULT NULL;
                END IF;
            END
            $$;
            """,
            # Reverse operation - remove column if it exists
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='customers_customer' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE customers_customer DROP COLUMN branch_id;
                END IF;
            END
            $$;
            """
        ),
    ]