# Generated by Django 5.2.7 on 2025-11-02 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('superadmin', '0003_business_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.business'),
        ),
    ]
