# Generated by Django 5.2.7 on 2025-11-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_business'),
    ]

    operations = [
    ]
