# Generated by Django 5.2.6 on 2025-10-31 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('superadmin', '0002_securityevent_created_at_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='superadmin.business'),
        ),
        migrations.AddField(
            model_name='sale',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='superadmin.business'),
        ),
    ]
