# Generated by Django 5.2.6 on 2025-11-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_cart_branch_remove_cart_created_by_and_more'),
        ('superadmin', '0004_branch_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='superadmin.branch'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='superadmin.branch'),
        ),
        migrations.AddField(
            model_name='refund',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='superadmin.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='superadmin.branch'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='superadmin.branch'),
        ),
    ]