# Generated by Django 5.2.6 on 2025-11-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_cart_branch_cartitem_branch_refund_branch_and_more'),
        ('superadmin', '0004_branch_manager'),
    ]

    operations = [
        # Check if the columns exist before adding them
        migrations.RunSQL(
            # Forward operation - only add columns if they don't exist
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_cart' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE sales_cart 
                    ADD COLUMN branch_id integer REFERENCES superadmin_branch(id) DEFAULT NULL;
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_cartitem' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE sales_cartitem 
                    ADD COLUMN branch_id integer REFERENCES superadmin_branch(id) DEFAULT NULL;
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_refund' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE sales_refund 
                    ADD COLUMN branch_id integer REFERENCES superadmin_branch(id) DEFAULT NULL;
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_sale' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE sales_sale 
                    ADD COLUMN branch_id integer REFERENCES superadmin_branch(id) DEFAULT NULL;
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_saleitem' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE sales_saleitem 
                    ADD COLUMN branch_id integer REFERENCES superadmin_branch(id) DEFAULT NULL;
                END IF;
            END
            $$;
            """,
            # Reverse operation - remove columns if they exist
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_cart' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE sales_cart DROP COLUMN branch_id;
                END IF;
                
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_cartitem' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE sales_cartitem DROP COLUMN branch_id;
                END IF;
                
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_refund' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE sales_refund DROP COLUMN branch_id;
                END IF;
                
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_sale' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE sales_sale DROP COLUMN branch_id;
                END IF;
                
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_saleitem' AND column_name='branch_id'
                ) THEN
                    ALTER TABLE sales_saleitem DROP COLUMN branch_id;
                END IF;
            END
            $$;
            """
        ),
    ]