# Generated by Django 5.2.6 on 2025-11-08 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_add_branch_fields'),
        ('superadmin', '0004_branch_manager'),  # Make sure we have the latest superadmin models
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='superadmin.business'),
        ),
    ]