# Generated by Django 5.2.6 on 2025-11-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_add_missing_business_field_to_saleitem'),
        ('superadmin', '0004_branch_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='superadmin.business'),
        ),
    ]