# Generated by Django 5.2.6 on 2025-11-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_add_business_field_to_cart'),
        ('superadmin', '0004_branch_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='superadmin.business'),
        ),
    ]