# Generated by Django 5.2.6 on 2025-11-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_add_business_field_to_cartitem'),
    ]

    operations = [
    ]
