# Generated by Django 5.2.6 on 2025-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_add_sale_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
