# Generated by Django 5.2.7 on 2025-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_format',
            field=models.CharField(choices=[('code128', 'Code 128 (High Density)'), ('ean13', 'EAN-13 (Retail Standard)'), ('upca', 'UPC-A (Retail Standard)')], default='code128', max_length=20),
        ),
    ]
