# Generated by Django 5.2.6 on 2025-10-31 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_barcode_format'),
        ('superadmin', '0002_securityevent_created_at_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='superadmin.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='superadmin.business'),
        ),
        migrations.AddField(
            model_name='unit',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='superadmin.business'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('business', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('business', 'name'), ('business', 'symbol')},
        ),
    ]
