# Generated by Django 5.2.6 on 2025-11-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20251104_1003'),
    ]

    operations = [
        # Removed duplicate AlterUniqueTogether operation to avoid conflict
        # The unique_together constraint is already set in migration 0005
    ]