# Generated by Django 5.2.6 on 2025-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_unique_together'),
        ('superadmin', '0003_alter_business_business_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        # Safely handle unique constraint change using RunSQL to avoid conflicts
        migrations.RunSQL(
            # Forward operation - drop existing constraint if it exists, then add new one
            """
            -- Drop the existing unique constraint if it exists
            ALTER TABLE products_product DROP CONSTRAINT IF EXISTS products_product_sku_uniq;
            ALTER TABLE products_product DROP CONSTRAINT IF EXISTS products_product_sku_3c51a516_uniq;
            -- Add the new unique constraint
            ALTER TABLE products_product ADD CONSTRAINT products_product_business_sku_uniq UNIQUE (business_id, sku);
            """,
            # Reverse operation - drop new constraint and restore old one
            """
            -- Drop the new unique constraint
            ALTER TABLE products_product DROP CONSTRAINT IF EXISTS products_product_business_sku_uniq;
            -- Restore the old unique constraint
            ALTER TABLE products_product ADD CONSTRAINT products_product_sku_3c51a516_uniq UNIQUE (sku);
            """
        ),
        migrations.RemoveField(
            model_name='unit',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode_format',
            field=models.CharField(choices=[('code128', 'Code 128 (High Density)'), ('ean13', 'EAN-13 (Retail Standard)'), ('upca', 'UPC-A (Retail Standard)')], default='code128', max_length=20),
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]