# Generated by Django 5.2.6 on 2025-11-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_unit_options_remove_category_branch_and_more'),
        ('superadmin', '0004_branch_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='superadmin.branch'),
        ),
    ]