# Generated by Django 5.2.6 on 2025-11-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_branch'),
    ]

    operations = [
    ]
